// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type User struct {
	ID        string       `json:"id"`
	AccountID string       `json:"account_id"`
	Password  string       `json:"password"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type UserDetail struct {
	ID        string       `json:"id"`
	UserID    string       `json:"user_id"`
	Nickname  string       `json:"nickname"`
	Authority int8         `json:"authority"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}
