// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"
	"database/sql"
)

const addUser = `-- name: AddUser :execresult
INSERT INTO users (
  id, account_id, password
) VALUES (
  ?, ?, ?
)
`

type AddUserParams struct {
	ID        string `json:"id"`
	AccountID string `json:"account_id"`
	Password  string `json:"password"`
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addUser, arg.ID, arg.AccountID, arg.Password)
}

const addUserDetail = `-- name: AddUserDetail :execresult
INSERT INTO user_details (
  id, user_id, nickname, authority
) VALUES (
  ?, ?, ?, ?
)
`

type AddUserDetailParams struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	Nickname  string `json:"nickname"`
	Authority int8   `json:"authority"`
}

func (q *Queries) AddUserDetail(ctx context.Context, arg AddUserDetailParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addUserDetail,
		arg.ID,
		arg.UserID,
		arg.Nickname,
		arg.Authority,
	)
}

const getUser = `-- name: GetUser :one
SELECT id, account_id, password, created_at, updated_at, deleted_at FROM users
 WHERE account_id = ?
  AND  deleted_at IS NULL
`

func (q *Queries) GetUser(ctx context.Context, accountID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, accountID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserDetails = `-- name: GetUserDetails :one
SELECT id, user_id, nickname, authority, created_at, updated_at, deleted_at FROM user_details
 WHERE user_id = ?
  AND  deleted_at IS NULL
`

func (q *Queries) GetUserDetails(ctx context.Context, userID string) (UserDetail, error) {
	row := q.db.QueryRowContext(ctx, getUserDetails, userID)
	var i UserDetail
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Nickname,
		&i.Authority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
